server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server7002
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: false
  instance:
    hostname: eureka7002.com
  server:
    enable-self-preservation: false
