server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:JunTech/springcloud-config.git
          search-paths:  #          搜索目录
            - springcloud-config
      label: master #搜索分支
eureka:
  instance:
    instance-id: cloud-config-server
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka