server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_path
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
            - After=2020-05-22T11:38:14.836+08:00[Asia/Shanghai]  #表示要在这个时间之后才会生效
            - Method=GET,POST
#            - Cookie=username,juntech
#            - Host=**.juntech.top
#            - Method=GET
        - id: payment_path
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            - After=2020-05-22T11:38:14.836+08:00[Asia/Shanghai]  #表示要在这个时间之后才会生效
            - Method=GET,POST
#            - Query=uname, \d+  #要有参数 uname且参数值是正整数才行
#            - Cookie=username,juntech
#            - Host=**.juntech.top
#            - Method=GET
          filters:
            - AddRequestParameter=X-Request-Id,1024
#  cloud:
#    gateway:
#      routes:
#        - id: payment_route   #路由匹配id
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
#          predicates:                #断言
#            - Path=/payment/get/**
#
#      - id: payment_route2
#        uri: http://localhost:8002
#        predicates:
#          - Path=/payment/discoveryclient/**
eureka:
  instance:
#    hostname: localhost
    prefer-ip-address: true
    instance-id: cloud-gateway
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka