server:
  port: 7001
spring:
  application:
    name: cloud-eureka-server7001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka7001.com